version: '3.7'

# 网络配置
networks:
  backend:
    driver: bridge


# 服务容器配置
services:

  prometheus:
    image: prom/prometheus:latest

    container_name: prometheus
    restart: always

    environment:
      - TZ=asia/shanghai
    volumes:
    # 将 prometheus 配置文件挂载到容器里
      - ./prometheus/:/etc/prometheus
    ports:
    # 设置容器9090端口映射指定宿主机端口，用于宿主机访问可视化web
      - "9090:9090"
    deploy:
      resources:
        limits:
          memory: 4G
    networks:
      - backend

  node-exporter:
    image: prom/node-exporter
    container_name: exporter
    ports:
      - 9010:9100
    restart: always
    volumes:
      - ./exporter/proc/:/host/proc:ro
      - ./exporter/sys/:/host/sys:ro
      - ./exporter/:/rootfs:ro
    networks:
      - backend

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    hostname: grafana
    restart: always
    ports:
      - 3000:3000
    volumes:
      # 配置文件
      - ./grafana/conf:/etc/grafana
      # 数据文件
      - ./grafana/var:/var/lib/grafana
    networks:
      - backend

